version: '3.8'

services:
  web:
    image: registry.gitlab.com/zumbidoalasca/lp:latest
    networks:
      - traefik_default
    deploy:
      replicas: 1 
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.ameii-lp-main321.rule=Host(`ameii.com.br`)
        - traefik.http.routers.ameii-lp-main321.entrypoints=websecure
        - traefik.http.routers.ameii-lp-main321.middlewares=cors-ameii-lp-main321@docker
        - traefik.http.routers.ameii-lp-main321.tls.certresolver=myresolver
        - traefik.http.routers.ameii-lp-main321.service=ameii-lp-main321
        - traefik.http.services.ameii-lp-main321.loadbalancer.server.port=3000
        - traefik.http.middlewares.cors-ameii-lp-main321.headers.accessControlAllowOrigin=*
        - traefik.http.middlewares.cors-ameii-lp-main321.headers.accessControlAllowCredentials=true

networks:
  traefik_default:
    driver: overlay